CREATE TABLE authors (
  id INTEGER GENERATED ALWAYS AS INDENTITY PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
)

CREATE TABLE games (
  id INTEGER GENERATED ALWAYS AS INDENTITY PRIMARY KEY,
  multiplayer VARCHAR(100) NOT NULL,
  last_played_at DATE NOT NULL,
  publish_date DATE NOT NULL,
  archived BOOLEAN NOT NULL DEFAULT false,
  FOREIGN KEY (author_id) REFERENCES authors(id)
);

